language: python
python:
  - "3.8.3"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade coveralls pytest-cov pytest
  - pip install -e .

# command to run tests
script:
  - python -m pytest -v --cov synbiopython --cov-report term-missing

after_success:
  - coveralls
