language: python
python:
  - "3.7.1"
  
before_install:
  - python -m pip install pip==18.1
  
# command to install dependencies
install:
  - pip install coveralls pytest-cov==2.6 pytest==4.0.2
  - pip install -e .
  
# command to run tests
script:
  - python -m pytest -v --cov synbiopython --cov-report term-missing

after_success:
  - coveralls
