language: python
python:
  - "3.7"

# command to install dependencies
before_install:
  - pip --version
  - pip install --upgrade pip==19.3.1
  - pip --version
  - pip install --upgrade pytest pytest-cov coveralls
install:
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov synbiopython --cov-report term-missing

after_success:
  - coveralls
