language: python
python:
  - "3.8.3"

# command to install dependencies
before_install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install --upgrade pytest pytest-cov coveralls
install:
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov synbiopython --cov-report term-missing

after_success:
  - coveralls
